name: Build and Push Docker Image
on: [push]  # 触发条件（推送代码时）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 指定Go版本

      - name: init Go mod
        run: go mod tidy
        
      - name: Build Go Binary
        run: go build -o /cmd/main main.go  # 替换为你的主程序路径

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mysqlproject:latest
